services:
  nats:
    image: nats:2.10.20-alpine
    command:
      - --js
      - --http_port=8222
      - --server_name=greentic-nats
      - --sd=/data
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats-data:/data
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8222/healthz || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  redis:
    image: redis:7.2-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  ingress:
    image: nginx:1.27-alpine
    depends_on:
      nats:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./ingress/default.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8080/healthz | grep -q alive"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

volumes:
  nats-data:
